# -*- coding: utf-8 -*-
"""Copy of Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tlGCdX4cgzulv-SucrDb0RGvgt9ck_Ok
"""

def swap_values(x, y):
    # Check if both x and y are numeric
    if not (isinstance(x, (int, float)) and isinstance(y, (int, float))):
        return -1

    # Swap the values using tuple unpacking
    x, y = y, x

    # Print the swapped values
    print("Swapped values: x =", x, ", y =", y)